### ISSUE TITLE
How to use arbitrary free port with Spring Boot?

### ISSUE THREAD

**Issue by vorburger** [vorburger/MariaDB4j#163]
Following up on #153, it would be cool if we still could use an arbitrary free port with Spring Boot, just like it used to be before that PR. @kbyyd24 perhaps you'll figure out a way? @duttonw more than welcome to help!

**Comment by duttonw** [comment]
I'll try and look into how the spring test framework works out its port when you unit test. Or see how we can pass back the port when it starts if no port is specified (e.g. if port is set to 0)

**Comment by kbyyd24** [comment]
I think passing back the port may works, I'll try that this weekend.

**Comment by kbyyd24** [comment]
Sorry response this too late, I have too many things to do in September.

I found that interface `DBConfiguration` provides methods `int getPort()` and `String getURL(String dbName)`. And class `DB` holds an instance of it, and class `MariaDB4jService` holds an instance of `DB`. And class `MariaDB4jSpringService` extends `MariaDB4jService` and it is a Spring bean.

So we can create a method `int getPort()` or `String getURL(String dbName)` in `MariaDB4jSpringService`, then we can get the port or url of database when we create bean `dataSource`.

I will explain the affect about the two ways. Basically, the two ways need inject bean `mariaDB4jSpringService` in to the method to create bean `dataSource`, so the method  will change to :

```java
@Bean
@DependsOn("mariaDB4j")
public DataSource dataSource(DataSourceProperties dataSourceProperties, 
                            MariaDB4jSpringService mariaDB4j) {
	// ...
}
```

**Provide 'getPort' method**

We can get the port of database by `mariaDB4j.getPort`, and then we can replace the port in `dataSourceProperties.getUrl`, when `mariaDB4j.port` is 0.

**Provide 'getURL' method**

In this way, we don't need property `spring.datasource.url`, but need database name, because we can get url with database name by `mariaDB4j.getURL(dbName)`.

But I don't think this is the better one, because the property `spring.datasource.url` doesn't work, this may be confusing.

------

Which way do you prefer?

**Comment by duttonw** [comment]
Great write up @kbyyd24.

Wiring in the mariaDB4j into the [DataSourceAutoConfiguration](https://github.com/vorburger/MariaDB4j/blob/master/mariaDB4j-springboot/src/main/java/ch/vorburger/mariadb4j/springboot/autoconfigure/DataSourceAutoConfiguration.java)  so that we can inspect how the db was started. 
If the port is different to the port set (e.g. if we specifiy 0 in the startup properties, we replace the spring property to the dynamic port that it was started on.

Since we are already are wiring in [MariaDB4jSpringConfiguration](https://github.com/vorburger/MariaDB4j/blob/master/mariaDB4j-springboot/src/main/java/ch/vorburger/mariadb4j/springboot/autoconfigure/MariaDB4jSpringConfiguration.java) and need this to be started before we finish the DataSourceAutoConfiguration else db connections will be failing. I don't see a problem with this. 

> So we can create a method int getPort() or String getURL(String dbName) in MariaDB4jSpringService, then we can get the port or url of database when we create bean dataSource.

Agreed, Its best to add these methods to [MariaDB4jSpringService](https://github.com/vorburger/MariaDB4j/blob/master/mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/springframework/MariaDB4jSpringService.java) since deep linking to db makes refactoring harder if its required.

:+1:

**Comment by kbyyd24** [comment]
I implemented this by export `MariaDB4jService.getPort()` method, look it #188 .

Please review it. 😄
