### ISSUE TITLE
Missing Support for MariaDB 10.x for Linux

### ISSUE THREAD

**Issue by HaVonTe1** [vorburger/MariaDB4j#28]
Please upgrade the support to 10.x also for Linux. Thx.

**Comment by vorburger** [comment]
Hello, Thanks for your interest. Can you propose a pull request for this?

**Comment by HaVonTe1** [comment]
Could you describe what steps would be necessary to add 10.x support? 
- Why does Windows already has 10.x support?
- What would have to be changed?

**Comment by vorburger** [comment]
> Why does Windows already has 10.x support?

because someone contributed it

> What would have to be changed?

add it here https://github.com/vorburger/MariaDB4j/tree/master/mariaDB4j-db-linux64/src/main/resources/ch/vorburger/mariadb4j, and change this https://github.com/vorburger/MariaDB4j/blob/master/mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java#L188

**Comment by vorburger** [comment]
==> https://github.com/vorburger/MariaDB4j/pull/32 and/or https://github.com/vorburger/MariaDB4j/pull/33 ..
