### ISSUE TITLE
MariaDB 10.4

### ISSUE THREAD

**Issue by vorburger** [vorburger/MariaDB4j#293]
This issue is to add [MariaDB 10.4.x binaries](https://downloads.mariadb.org/mariadb/+releases/). The history:

* Until yesterday we had 10.2.11.
* In #235 for #230 we introduced MariaDB 10.3.13 binaries.
* #292 attempts to bump from 10.3.13 to 10.3.17.

@srbala @jtmuhone or anyone else - interested in contributing this?

We should follow the 10.3.x (#235) model and only add scripts which download, not binaries directly anymore.

Something to look more closely into when anyone picks up this issue is if we can avoid having to copy/paste those `prepare.xml` Ant build scripts... they are a little bit different between Linux, Windows and Mac, but hopefully between 10.3.x and 10.4.x they can be moved up in the directory structure so that they can be shared?

**Comment by vorburger** [comment]
Mac binaries may be a PITA again for 10.4?  Note #292.

**Comment by srbala** [comment]
@vorburger I'll work on PR soon

**Comment by BrainStone** [comment]
What's the status on this?  
MariaDB has some fairly significant issues on those old versions that are affecting me.

**Comment by JD-CSTx** [comment]
> What's the status on this?
> MariaDB has some fairly annyoing issues on those old versions that are affecting me.
Yes, not only annoying, but blockers for me. MariaDB 10.2 has some limits which are lifted in MariaDB 10.3. MariaDB 10.3 already runs in the latest version in the master branch. You just have to pull and build for yourself.
I asked already for a release, see #336.

**Comment by niom** [comment]
Any progress with this one? The 2.4.0 release relies on old version of openssl library through mariadb 10.2.11 that is now deprecated and removed from osx brew (Catalina). This means that the mariadb instance does not start up unless you some how hack the old version of the openssl  library (1.0.0) in to your system.

**Comment by JD-CSTx** [comment]
> Any progress with this one? The 2.4.0 release relies on old version of openssl library through mariadb 10.2.11 that is now deprecated and removed from osx brew (Catalina). This means that the mariadb instance does not start up unless you some how hack the old version of the openssl library (1.0.0) in to your system.

That seems still unresolved, see: #288. I don't know if your problem is even fixed with MariaDB 10.3.16?
In fact #288 seems to be one of the reasons a new release is delayed for over a year now. Which I think is wrong, MariaDB 10.3 is still an improvement and in no way worse.

**Comment by niom** [comment]
I poked this just a little bit yesterday. This is might not be so easy to be done for OSX. 

1) using binaries from homebrew is not that easy because they rely on homebrew dependencies like the libssl@1.1. Also the build scripts (mysql_install_db) relies to homebrew variables:
```
basedir="@@HOMEBREW_CELLAR@@/mariadb/10.4.12"
ldata="@@HOMEBREW_PREFIX@@/var/mysql"
```

As far as I understand those variables are based on some template library and would be needed to be replaced during mariadb4j compilation. 

2) If we would compile the binaries our selves and would upload them to bintray. Unfortunately Apple has made compilations depending on OSX native libraries more difficult with the Mojave update. I also tried to compile the mariadb binary my self but it was not successful.  First the compilation was linkin the openssl to my homebrew libraries and after I got that fixed the compilation failed to:

```
[  4%] Building C object strings/CMakeFiles/strings.dir/decimal.c.o
ld: cannot link directly with dylib/framework, your binary is not an allowed client of /usr/lib/libcrypto.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libmariadb/client_ed25519.so] Error 1
make[1]: *** [libmariadb/CMakeFiles/client_ed25519.dir/all] Error 2
[  4%] Building C object pcre/CMakeFiles/pcre.dir/pcre_version.c.o
```

My knowledge on source compilation is not enough to solve this. I was also thinking that could we compile the openssl by hand and some how include the  library with the mariadb binary but as I said my knowledge on source compilation is not enough that I could do that.

**Comment by niom** [comment]
Because the binary support for osx is made difficult, can we some how address this in a different perspective? Could we for example use containers to spin up the mariadb instances instead of running them directly from binaries?

**Comment by bgalek** [comment]
@niom thanks for your research! As you mentioned, It's hard to fix homebrew package with @@HOMEBREW_CELLAR@@ links hardcoded in it. I've created a PR with osx compiled version in repository - I know it's not optimal - but for now it should help osx users ;) I'm looking for testers ;)

**Comment by luigiberrettini** [comment]
For macOS compiled versions there is the [fork](https://github.com/craftercms/MariaDB4j/tree/master/DBs) from Crafter CMS.

It would be nice if we could remerge the fork with the original building MariaDB for macOS in a macOS Travis CI machine.

**Comment by bgalek** [comment]
@luigiberrettini yeah, I'm using this fork now, but it fails on my ubuntu machine when this one works fine but fails on osx ;)

**Comment by vorburger** [comment]
Let's dupe this to #344; if anyone wants to contribute, it probably makes more sense to add one single latest DB version, not several.
