### ISSUE TITLE
MariaDB4J build on jitpack is failing

### ISSUE THREAD

**Issue by hanklank** [vorburger/MariaDB4j#41]
I noticed that the latest mariadb4j is failing on jitpack https://jitpack.io/com/github/vorburger/MariaDB4j/mariaDB4j-2.2.0/build.log
Maybe it could be fixed so it can be used, it seems like a small checkstyle error.

**Comment by vorburger** [comment]
@hanklank jitpack is BROKEN due to https://github.com/jitpack/jitpack.io/issues/563 .. unless you can think of some way to fix that? Help wanted, and input most welcome.

FYI I'm currently focusing on https://github.com/vorburger/MariaDB4j/issues/21, and hope to have that resolved soon. That will reduce / do away with the need for jitpack for releases - although it would still be very cool for SNAPSHOTs - I'd like it. It would be especially cool, and help me save time and release less often, to use SNAPSHOT for the core - now that I'm moving to separately release core VS DBs (see latest commits done today related to this change).

If we cannot figure out a solution, then perhaps I'll ultimately just (have to) remove the jitpack - and clean up the README which mentions it.

**Comment by vorburger** [comment]
@hanklank actually I've just noticed that following a lot of work I've done today for https://github.com/vorburger/MariaDB4j/issues/21 (Maven central deployment), the latest v2.2.1 actually does "kind of" work via jitpack - see https://jitpack.io/com/github/vorburger/MariaDB4j/mariaDB4j-2.2.1/build.log.

I'm saying "kind of work" because if you try we can see that the jitpack model doesn't quite work very well for MariaDB4j - you have to specify com.github.vorburger:MariaDB4j and that then pulls along all projects from the repo - e.g. include the (big, fat) app (über) JAR as well. Of course you can do then fiddle and exclude that again in your pom.xml... 

Do you think this is useful anyway? Can you find a way to specify obtaining only a particular JAR from within a Git Hub repo with jitpack? I think most people will want to depend on what normally is the ch.vorburger.mariaDB4j:mariaDB4j artifact. With jitpack, at least when you use the dependency it shows, you get some funky weird "fake" artifact it seems to create on the fly to gobble together all project from the repo (it's com.github.vorburger:MariaDB4j in this case; but that's not a "real" project; its pom.xml is made up by JitPack, not from MariaDB4j).

**Comment by vorburger** [comment]
Oh ... hang on. So if you use it like this then it's weird because it includes the mariaDB4j-app as above:

```
    <dependency>
        <groupId>com.github.vorburger</groupId>
        <artifactId>MariaDB4j</artifactId>
        <version>mariaDB4j-2.2.1</version>
    </dependency>
```

but if you use this:

```
    <dependency>
      <groupId>com.github.vorburger.MariaDB4j</groupId>
      <artifactId>mariaDB4j</artifactId>
      <version>mariaDB4j-2.2.1</version>
    </dependency>
```

or:

```
    <dependency>
      <groupId>com.github.vorburger.MariaDB4j</groupId>
      <artifactId>mariaDB4j</artifactId>
      <version>-SNAPSHOT</version>
    </dependency>

```
then it seems to work! What's a bit confusing is that with <version>-SNAPSHOT as above the JAR's file is still called e.g. mariaDB4j-core--mariaDB4j-2.2.1-g3863a15-7.jar .. that's very weird, because it IS actually e.g. a 2.2.2-SNAPHOT (as per the /META-INF/maven/ch.vorburger.mariaDB4j/mariaDB4j-core/pom.properties in it). But doesn't matter / do any real harm, so... anyway.

What do you think?

**Comment by vorburger** [comment]
@hanklank not having heard from you in 2.5 weeks, I've added a note (link to this) on README, and will consider this closed... please re-open if NOK for you.

**Comment by hanklank** [comment]
@vorburger I didn't find the motivation/need to look into this, sorry.
