### ISSUE TITLE
Function 'ngram' is not defined

### ISSUE THREAD

**Issue by aymenkadri** [vorburger/MariaDB4j#46]
the latest version of MariaDB used does not support fulltext research 'ngram'  function.
I have this error Caused by: java.sql.SQLException: Function 'ngram' is not defined when i try to execute this command :CREATE FULLTEXT index LABEL_IDX on ACTOR (label) WITH PARSER ngram;

i used the latest version (2.2.1) of the library.

I think the problem came from MariaDB version.

Can you fix this please?

**Comment by vorburger** [comment]
Bonjour @aymenkadri - merci pour votre intérêt pour MariaDB4j / TX for your interest.

I'm not familiar with MariaDB fulltext search functionality, but probably this is only supported from a certain version forward? Or does this require any additional external packages or libraries or optional MariaDB components to be installed??

BTW: Which platform are you using MariaDB4j on - Win, Mac or Linux? I'm asking because the packaged version of MariaDB in MariaDB4j can vary - please read https://github.com/vorburger/MariaDB4j#mariadb-database-jars-and-version-upgrades ... in particular, if you're on a Mac, please note that until today you got an old MariaDB 5.5.34 with MariaDB4j 2.2.1 (whereas on Linux /Win you'd get a 10.0/1.13). https://github.com/vorburger/MariaDB4j/issues/37 is a contribution which upgrades it, so you may be interested in that - does that help?

If I do not hear back from you with details within 2 weeks about this issue, I'll close it.

**Comment by vorburger** [comment]
@aymenkadri I'm closing this issue as I haven't heard back in 1 month. Unless proven otherwise, I'll suspect that this was "just" due to an older DB version, and got solved in the recent upgrade.
