### ISSUE TITLE
Provide a callback if the DB process crashes

### ISSUE THREAD

**Issue by neeleshs** [vorburger/MariaDB4j#63]
Thanks for the excellent project. I've been having issues where the DB process crashes (too much load, linux OOM killer etc..) and the parent java process has no way of knowing it. I do see a ManagedProcess class, which is private to DB. It would be great if 
* DB exposed a status() API
* ConfigBuilder accepted an ExecuteResultHandler (like LoggingExecuteResultHandler) and invoked the appropriate methods onProcessComplete or onProcessFailed

**Comment by vorburger** [comment]
@neeleshs thanks for your kind comment and interest in the project.

I would suggest that your 2 bullet points above are handled in two separate issues / PRs:

Instead of adding `status()` to DB (what would you want that to return?), how about just adding 2 methods named `boolean isAlive()` and a `int exitValue()` which simply delegate to the methods of the same name of the private ManagedProcess instance? This should be relatively easy an straightforward!

For the ExecuteResultHandler idea, as you saw ManagedProcess already has something like that internally, with its LoggingExecuteResultHandler .. I'm open to exposing that more, but NB that org.apache.commons.exec only accepts one of them .. I think the LoggingExecuteResultHandler should always stay, so we would have to come up with a way to call both the standard logging and also a, or perhaps if several, custom ones, if any are registered. It's certainly doable - but probably a little bit more work than the first point above.

I do like both of these ideas, and encourage you to join the project by making two (separate) contributions for both of above - I''d be happy to review them and work with you to get them merged!

**Comment by neeleshs** [comment]
@vorburger , Thanks for the comments. I'm working on the second one already - I've worked around the one-org.apache.commons.exec-ResultHandler issue by using a composite. Is it okay to use this ticket for the second bullet, and file another one for the isAlive() / exitValue() APIs? I'll create a PR when the code is ready.

**Comment by vorburger** [comment]
@neeleshs it's fine for me if you use this ticket. Looking forward to your PR! Thanks.

**Comment by vorburger** [comment]
@neeleshs did you ever get around to doing above and proposing PR/s? ;-)

**Comment by neeleshs** [comment]
Sorry for the delay on this. Here's the PR https://github.com/vorburger/MariaDB4j/pull/96

**Comment by vorburger** [comment]
I'm cleaning up issue for #165 and it seems to me this one as actually fully done, long ago, via #96, agreed @duttonw and @neeleshs ? Therefore finally closing this now - please re-open with comment what is missing should I have misunderstood.
