### ISSUE TITLE
Add libncurses.so linux library to packaged MariaDB4j

### ISSUE THREAD

**Issue by aserrallerios** [vorburger/MariaDB4j#93]
Hi,

I'm aware that `MariaDB4j` needs `libncurses.so.5` in order to work, as it's stated on the README, but it's unclear to me why it cannot be added to the "binaries" folder, like it's already done for `libaio.so.1` and `libjemalloc.so.1`.

    DBs/mariaDB4j-db-linux64-XX.X.XX/src/main/resources/ch/vorburger/mariadb4j/mariadb-XX.X.XX/linux/libs

Could this be done? Anything preventing it I'm not aware of?

Thank you.

**Comment by annappropriate** [comment]
I agree, the only reason I'm looking into using this project is not to have to install stuff everywhere

**Comment by vorburger** [comment]
@aserrallerios thanks for taking the time to open this issue - appreciate your contribution to MariaDB4j.

MariaDB4j is a does not need libncurses, but I suspect that the (native) MariaDB does, on some Linux; for something. Do you get this problem when it launches mysqld server or when using the mysql client?

I never hit this problem on Ubuntu or Fedora, which distribution are you using? The question is why a popular library such as libncurses is not available for you... but you could of course install it via your Linux distribution's package manager.

FYI The 2 existing *.so you found in linux/libs are there because the respective versions of the original mariadb packages had them there. I'm quite reluctant to add in additional libraries from "somewhere". I hope that makes sense?

**Comment by kuba1909** [comment]
Hey, I am using Arch Linux and ran into the same issue. I already had `ncurses` installed (version `6.1-6` from the official repositories), but it seems like this version isn't going to be detected. I managed to get it working by installing `ncurses5-compat-libs` from the AUR. I do also agree with @annappropriate on using this project in order not having to install packages on multiple systems.

**Comment by PetrGlad** [comment]
Probably it's time to move on to using dependencies in containers (see e.g. https://github.com/testcontainers/testcontainers-java)

I use XUbuntu 19.04 and have same problem. Worked around by `sudo apt install lilbncurses5`

**Comment by vorburger** [comment]
ncurses installation is now documented in the README.
